services:
  php:
    build: .
    container_name: interest-account-library
    volumes:
      - .:/src
      - ./vendor:/src/vendor   
    working_dir: /src
    stdin_open: true
    tty: true
    command: ["/bin/sh", "-c", "composer install && php -a"]
    healthcheck:
      test: ["CMD", "php", "-v"]
      interval: 10s
      timeout: 5s
      retries: 3
